// tailwind.config.mjs
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'
  ],
  theme: {
    extend: {
      colors: {
        "error-dim": "#4e0309",
        "error": "#9f403d",
        "on-tertiary-fixed": "#484a47",
        "surface-container-low": "#f2f4f4",
        "secondary": "#5f5f5f",
        "surface-variant": "#dde4e5",
        "on-surface": "#2d3435",
        "inverse-primary": "#ffffff",
        "on-error-container": "#752121",
        "surface-container-highest": "#dde4e5",
        "error-container": "#fe8983",
        "on-tertiary": "#f9f9f4",
        "surface-dim": "#d3dbdd",
        "on-tertiary-container": "#5b5c59",
        "secondary-fixed": "#e3e2e2",
        "primary-fixed": "#e5e2e1",
        "surface-tint": "#5f5e5e",
        "on-secondary-fixed": "#3f3f3f",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#e3e2e2",
        "surface-container-high": "#e4e9ea",
        "primary-fixed-dim": "#d6d4d3",
        "on-secondary": "#faf8f8",
        "background": "#f9f9f9",
        "surface-bright": "#f9f9f9",
        "primary": "#5f5e5e",
        "secondary-dim": "#535353",
        "inverse-on-surface": "#9c9d9d",
        "on-error": "#fff7f6",
        "on-surface-variant": "#596061",
        "primary-dim": "#535252",
        "inverse-surface": "#0c0f0f",
        "tertiary-dim": "#525450",
        "on-primary-container": "#525151",
        "surface": "#f9f9f9",
        "surface-container": "#ebeeef",
        "tertiary": "#5e605c",
        "tertiary-fixed-dim": "#e5e6e1",
        "secondary-fixed-dim": "#d5d4d4",
        "on-secondary-fixed-variant": "#5b5b5b",
        "primary-container": "#e5e2e1",
        "on-primary-fixed-variant": "#5c5b5b",
        "on-primary": "#faf7f6",
        "tertiary-fixed": "#f4f4ef",
        "outline": "#757c7d",
        "outline-variant": "#acb3b4",
        "on-secondary-container": "#515252",
        "tertiary-container": "#f4f4ef",
        "on-primary-fixed": "#403f3f",
        "on-background": "#2d3435",
        "on-tertiary-fixed-variant": "#656763"
      },
      fontFamily: {
        "headline": ["Newsreader", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
    },
  },
  plugins: [],
}